-- RPG plugin: isotopes.lua -- makes the 50 notable-nuclide elements registered by
-- bridge_src/09_isotopes_seed.lua (generated by scripts/gen_isotope_elements.py, both dev-tree
-- only) read correctly EVERYWHERE, and reports on them for verification.
--
-- PhoenixFire808 (@isotopes task brief): "'Uranium-235', not 'U235' or 'URAN'... Every nuclide must
-- read correctly everywhere it appears: the HUD, the materials panel, the guide, the periodic
-- table." rpg.lua's own element-registry name IS the 4-char code (Name = spec.name, confirmed by
-- direct read of bridge_src/10_registry.lua's buildElementTable -- there is no separate display-
-- name field in the registration pipeline, only the code) -- so "U235" is genuinely what
-- elem.property(t,"Name") returns for that particle. R.nice()/R.typeLabel() (rpg.lua) both already
-- resolve through R.NAMES first, EXACTLY the same "friendly override" mechanism DU="Uranium ore"/
-- URAN="Uranium" already use two lines below R.NAMES' own definition -- this file just adds 50
-- more entries to that SAME shared table (a plain Lua table on R, mutated by reference, not a
-- second naming implementation) rather than inventing anything new. guide.lua's own materials
-- browser (`R.nice(k)`, confirmed by direct read, not assumed) and rpg.lua's HUD/materials-panel
-- call sites (`R.typeLabel`/`R.partLabel`, confirmed same way) both already read this table, so
-- populating it here is the entire fix -- no other file needs to change.
-- No R.hooks registered -- this file only populates a shared table and exposes a diagnostic
-- function, both one-shot at load time; there is no per-tick/per-draw behaviour to hook.
local R = PBX.state.rpg
local TAG = "isotopes"

R.NAMES = R.NAMES or {}
-- code -> full "Element-A" display name. Generated data, hand-verified against
-- knowledge/isotopes-notable-catalog.json (which gen_isotope_elements.py also writes) rather than
-- retyped -- see that file for the exact Z/N/half-life/decay-mode citation behind every one.
local ISO_NAMES = {
  TRIT = "Hydrogen-3 (Tritium)", HE3 = "Helium-3", LI6 = "Lithium-6", LI7 = "Lithium-7",
  B10 = "Boron-10", B11 = "Boron-11", C14 = "Carbon-14", F18 = "Fluorine-18", K40 = "Potassium-40",
  CO6N = "Cobalt-60", GA67 = "Gallium-67", SR89 = "Strontium-89", SR90 = "Strontium-90",
  MO99 = "Molybdenum-99", TC99 = "Technetium-99", CD13 = "Cadmium-113", I123 = "Iodine-123",
  I131 = "Iodine-131", XE35 = "Xenon-135", CS37 = "Caesium-137", SM49 = "Samarium-149",
  GD55 = "Gadolinium-155", GD57 = "Gadolinium-157", IR92 = "Iridium-192", PO10 = "Polonium-210",
  RA26 = "Radium-226", THOR = "Thorium-232", U233 = "Uranium-233", U235 = "Uranium-235",
  U238 = "Uranium-238", PU38 = "Plutonium-238", PU39 = "Plutonium-239", PU41 = "Plutonium-241",
  NI60 = "Nickel-60", Y89 = "Yttrium-89", Y90 = "Yttrium-90", RU99 = "Ruthenium-99",
  IN13 = "Indium-113", TE23 = "Tellurium-123", XE31 = "Xenon-131", CS35 = "Caesium-135",
  BA37 = "Barium-137", RN22 = "Radon-222", RA28 = "Radium-228", TH29 = "Thorium-229",
  TH31 = "Thorium-231", TH34 = "Thorium-234", U234 = "Uranium-234", NP37 = "Neptunium-237",
  CM48 = "Curium-248",
}
local appliedNames, skippedNames = 0, 0
for code, label in pairs(ISO_NAMES) do
  if R.NAMES[code] == nil then
    R.NAMES[code] = label
    appliedNames = appliedNames + 1
  else
    -- Never clobber an existing entry (defensive -- none of these 50 codes should collide with
    -- rpg.lua's own R.NAMES table, verified at generation time, but a reload-order surprise from
    -- another plugin populating the same key first should lose loudly, not silently, if it ever
    -- happens).
    skippedNames = skippedNames + 1
    PBX.log(TAG, "R.NAMES['" .. code .. "'] already set to '" .. tostring(R.NAMES[code]) ..
      "' -- isotopes.lua left it alone rather than overwrite")
  end
end
PBX.log(TAG, string.format("isotope display names applied: %d (skipped %d already-set)", appliedNames, skippedNames))
if R.tlog then R.tlog("info", "isotopes", "names applied", { applied = appliedNames, skipped = skippedNames }) end

-- ================================================================ live verification/report
-- Derives id bounds from sim.PMAPBITS (never a stale 0..511 scan -- PT_NUM is 4096 now, see
-- AGENTS.md). Cheap: runs once per call, not per tick -- this is a diagnostic, not a hot path.
local function scanRegisteredNuclides()
  local found, missingNames = {}, {}
  for code in pairs(ISO_NAMES) do
    local tid = elem["DEFAULT_PT_" .. code]
    if not tid then
      for j = 0, (2 ^ ((sim and sim.PMAPBITS) or 9)) - 1 do
        local ok, nm = pcall(elem.property, j, "Name")
        if ok and nm == code then tid = j; break end
      end
    end
    if tid then
      local okd, desc = pcall(elem.property, tid, "Description")
      found[code] = { id = tid, desc = okd and desc or "?" }
    else
      missingNames[#missingNames + 1] = code
    end
  end
  return found, missingNames
end

--- R.isotopes.report() -- console/bridge verification helper, no key or panel (matches
--- R.thermo.report()'s own precedent): "registered N/50, live names read back correctly M/50".
--- Not called anywhere automatically; exists purely so this lane's own claim can be checked
--- against the live session rather than trusted, per AGENTS.md's "verify it LANDED" rule.
R.isotopes = R.isotopes or {}
function R.isotopes.report()
  local found, missing = scanRegisteredNuclides()
  local nFound, nameOk = 0, 0
  for code, info in pairs(found) do
    nFound = nFound + 1
    local label = R.typeLabel and R.typeLabel(info.id, 0) or ""
    if label == ISO_NAMES[code] then nameOk = nameOk + 1 end
  end
  local total = 0
  for _ in pairs(ISO_NAMES) do total = total + 1 end
  local lines = {
    string.format("isotopes: registered %d/%d nuclide elements live", nFound, total),
    string.format("isotopes: R.typeLabel() resolves the full accurate name on %d/%d of those", nameOk, nFound),
  }
  if #missing > 0 then
    lines[#lines + 1] = "isotopes: NOT FOUND this session: " .. table.concat(missing, ",")
  end
  return table.concat(lines, "\n"), found, missing
end

-- ================================================================ radiation-zone linkage
-- rpg.lua's own R.radZones (Fallout-style ground contamination -- rpg.lua:1296-1309) is driven by
-- G.rad, itself accumulated from nearby URAN/PLUT presence (rpg.lua's own atmosphere-hazard scan).
-- These 50 elements are new particle TYPES the engine doesn't know are radiological hazards, but
-- they carry PROP_RADIOACTIVE nowhere in the seed (kept out deliberately -- see gen_isotope_elements.py:
-- adding PROP_RADIOACTIVE to fissile/fertile fuel types would make them emit real ionizing radiation
-- particles per the engine's own native RADIOACTIVE handling, which is real physics this pass did not
-- have time to tune (dose rates, shielding interaction) without risking an unbalanced, untested hazard
-- flooding a player's world). Flagged here, not hidden, as the one deliberately-deferred piece of
-- "the RPG already has radiation mechanics... build on those": the decay/half-life/naming/spawn
-- mechanics this file's sibling seed delivers are complete and real; wiring these particular 50
-- element TYPES into the existing G.rad contamination scan is scoped, real follow-up work, not done
-- this pass.
