-- RPG plugin: periodic.lua -- the periodic table + isotope chart, wired into the actual game.
-- PhoenixFire808, verbatim: "all of the periodic stuff that we did, the isotopes and the isotope
-- charts and all that" -- brought over from the sister project (D:/sandgame) rather than left
-- there. Owns exactly this file plus its lazy data file (periodic_data.lua, generated by
-- scripts/gen_isotope_data.py -- regenerate that, never hand-edit the data file).
--
-- NOT YET in R.PLUGINS (rpg.lua is not this lane's file to edit -- AGENTS.md). Same situation and
-- same fix telemetry.lua documented for itself: add "periodic" anywhere in the R.PLUGINS list
-- (before "ui" is not required -- this file calls nothing from ui.lua). Until that lands, load it
-- this session with `PBX.state.rpg.reloadPlugin("periodic")` after any F9 core reload.
--
-- LAZY DATA LOAD (the actual point of periodic_data.lua being a separate, unregistered file): the
-- 118-element/3,383-isotope table is only loadfile()'d the first time a player actually opens this
-- panel (loadIsotopeData() below), never at boot. See periodic_data.lua's own header and
-- scripts/gen_isotope_data.py's docstring for the full "why" and the measured size reduction.
--
-- ACCESSIBILITY -- PhoenixFire808, verbatim: "We don't want to have to push function hotkeys at
-- the top of our shit. We want button options for stuff. I hate having to push buttons on my
-- keyboard... My hand is broken." Every action here has a mouse path and NONE requires one:
-- opening (a persistent on-screen button, not a keybind), picking an element (click a cell),
-- paging isotopes (drag or click-to-seek scrollbar, or the mouse wheel), filtering (click a
-- filter chip), closing (an on-screen X). Escape also closes it as a convenience, exactly like
-- guide.lua, but is never the ONLY way to do anything.
local R = PBX.state.rpg
local TAG = "periodic"
-- FIXED 2026-09-02. This used to remove EVERY entry carrying this plugin's tag before appending,
-- which meant a plugin's SECOND hook on a given list silently deleted its FIRST. @audit proved
-- that killed the Replicator Core recovery feature outright -- it was registered, then destroyed
-- by a later registration in the same file, and nobody could see why the feature did nothing.
-- 29 plugins share this helper and several register 7-14 hooks, so an unknown number of features
-- have been quietly dead. The reload cleanup it was trying to do is still needed, so it now
-- happens ONCE per load, across every hook list, before any registration -- and hook() simply
-- appends, so a file can register as many hooks as it likes.
for _, __l in pairs(R.hooks or {}) do
  if type(__l) == "table" then
    for i = #__l, 1, -1 do
      if type(__l[i]) == "table" and __l[i].tag == TAG then table.remove(__l, i) end
    end
  end
end
local function hook(list, fn)
  list[#list + 1] = setmetatable({ tag = TAG }, { __call = function(_, ...) return fn(...) end })
end
local floor = math.floor
local function hitRect(r, x, y) return r and x >= r[1] and x < r[3] and y >= r[2] and y < r[4] end
local function textW(s) return #s * 6 end

-- ================================================================ persistent state (survives reloadPlugin)
local P = R.periodic or {}
R.periodic = P
P.open = P.open or false
P.view = P.view or "table"     -- "table" | "element"
P.z = P.z or nil               -- selected atomic number, element view only
P.scroll = P.scroll or 0       -- isotope-list scroll offset, element view only
P.filter = P.filter or "all"   -- "all" | "stable" | "radioactive" | "promoted" | "linked"
P.drag = nil                   -- not persisted across reload, matches guide.lua's own convention
P.dragBar = nil

-- ================================================================ lazy data load, measured
-- Loaded at most once per session (DATA caches on R.periodic.data); the panel simply cannot be
-- opened before this succeeds, so there is no "half-open with missing data" state to draw.
local function loadIsotopeData()
  if P.data then return P.data end
  local candidates = {
    "../scripts/lua/rpg_plugins/periodic_data.lua",
    "scripts/lua/rpg_plugins/periodic_data.lua",
    "D:/The-Powder-Toy/scripts/lua/rpg_plugins/periodic_data.lua",
    "D:/powder-toy/scripts/lua/rpg_plugins/periodic_data.lua",
  }
  local memBefore = collectgarbage("count")
  local t0 = os.clock()
  for _, path in ipairs(candidates) do
    local f = io.open(path, "r")
    if f then
      f:close()
      local chunk, lerr = loadfile(path)
      if not chunk then
        PBX.log(TAG, "periodic_data.lua load error at " .. path .. ": " .. tostring(lerr))
        if R.tlog then R.tlog("error", "periodic", "data loadfile failed", { path = path, err = tostring(lerr) }) end
      else
        local ok, tbl = pcall(chunk)
        if ok and type(tbl) == "table" and type(tbl.elements) == "table" then
          local t1 = os.clock()
          local memAfter = collectgarbage("count")
          tbl.byZ = {}
          for _, e in ipairs(tbl.elements) do tbl.byZ[e.z] = e end
          P.data = tbl
          P.loadMs = (t1 - t0) * 1000
          P.loadKB = memAfter - memBefore
          PBX.log(TAG, string.format("isotope data loaded from %s: %d elements, parse+build %.1fms, +%.0fKB",
            path, #tbl.elements, P.loadMs, P.loadKB))
          if R.tlog then R.tlog("info", "periodic", "isotope data loaded", {
            path = path, elements = #tbl.elements, load_ms = P.loadMs, mem_kb = P.loadKB }) end
          return tbl
        else
          PBX.log(TAG, "periodic_data.lua ran but returned an unexpected value from " .. path)
          if R.tlog then R.tlog("error", "periodic", "data chunk returned bad value", { path = path, ok = ok }) end
        end
      end
    end
  end
  PBX.log(TAG, "periodic_data.lua not found on any candidate path -- periodic table unavailable this session")
  if R.tlog then R.tlog("error", "periodic", "data file not found on any candidate path", {}) end
  return nil
end

-- ================================================================ real-game linkage (HAND-CURATED,
-- verified against this repo's own source -- not derived from the sister project's promoted_materials,
-- which names ITS OWN C#/materials.json ids, not Powder Toy Lua element codes. A player asking "does
-- this nuclide exist in MY world" needs the Powder Toy answer, not the sandgame one.)
-- Each entry: element symbol -> { code = primary in-game element code to check with R.has()/R.colourOf(),
-- alt = optional second code, note = how to actually get it, verified against rpg_plugins/world.lua's
-- veins and rpg_plugins/acq_energy.lua's recipes (both read directly before writing this table).
local LINK = {
  H  = { code = "DEUT", note = "Deuterium (H-2) is mineable directly as DEUT -- deep veins, world.lua. "
                              .. "Tritium (H-3) shares its fusion_fuel role but has no separate in-game "
                              .. "material yet (flagged, not built this pass)." },
  U  = { code = "URAN", alt = "DU", note = "Uranium ore mines as URAN (or DU where depleted-uranium is "
                              .. "installed). Craft UO2 fuel pellets at a furnace (4x ore + 1 coal) for "
                              .. "reactors. This world does not model U-235 vs U-238 as separate materials "
                              .. "-- both are the same bulk ore here." },
  Pu = { code = "PLUT", note = "Bred at an Advanced Lab bench: Platinum (PTNM) catalyzes Solid Isotope "
                              .. "(ISZS) into Plutonium -- the real native PTNM+ISZS engine reaction, "
                              .. "gated behind an online reactor." },
  Li = { code = "LITH", note = "Mines directly as LITH." },
  Hg = { code = "MERC", note = "Mines directly as MERC, swamp biomes only." },
  Pt = { code = "PTNM", note = "Mines directly as PTNM -- also the plutonium-breeding catalyst above." },
  Po = { code = "POLO", note = "Made in the Isotope Forge: heat a Proton (PROT) particle above 310K -- "
                              .. "the real native PROT.cpp engine transition." },
}
-- The 5 nuclides ACCRETION (the sister project) promoted to first-class C#/materials.json entries.
-- Shown as citation/context only -- these are sandgame ids (uranium_235 etc.), not Powder Toy codes;
-- the LINK table above is the actual "does this exist in THIS game" answer.
local function promotedNoteFor(data, nuclideSymbol)
  return data.promoted and data.promoted[nuclideSymbol]
end

-- ================================================================ family colours (chemistry-chart
-- convention, not a physical measurement -- picked for readability/contrast, same status as any
-- printed periodic table's colour key)
local FAMILY_COLOUR = {
  alkali_metal          = { 255, 140, 140 },
  alkaline_earth        = { 255, 190, 120 },
  transition_metal      = { 230, 210, 140 },
  post_transition_metal = { 150, 205, 150 },
  metalloid             = { 140, 205, 205 },
  nonmetal              = { 140, 190, 255 },
  halogen               = { 205, 160, 255 },
  noble_gas             = { 255, 150, 220 },
  lanthanide            = { 255, 175, 230 },
  actinide              = { 190, 255, 190 },
  transactinide         = { 180, 180, 180 },
}
local function familyColour(fam) local c = FAMILY_COLOUR[fam]; return c and c[1] or 190, c and c[2] or 190, c and c[3] or 190 end

-- ================================================================ geometry (mirrors guide.lua's own
-- SAFE-derived panel box exactly, so the two panels feel like the same UI system)
local SAFE = R.SAFE or { x = 4, y = 16, w = 604, h = 344 }
local GX, GY, GW, GH = SAFE.x + 2, math.max(SAFE.y + 2, 34), SAFE.w - 4, 320
local BY = GY + 18
local BOT = GY + GH - 4
local SBW = 6

-- Persistent open/close toggle button. Placed just below the minimap's own footprint (minimap box
-- is x=502..604, y=2..82 when R.minimap is on -- rpg.lua's drawMinimap) so it is never overlapped
-- either way, and left of the right edge so it never collides with the right alert column, which
-- rpg.lua's own HUD-layout comment states stops at x=498.
local TOGGLE = { GX + GW - 90, 88, GX + GW, 104 }

function R.openPeriodic(zOrNil)
  if not loadIsotopeData() then
    if R.say then R.say("Periodic table data failed to load -- see autorun-runtime.log") end
    return
  end
  P.open = true
  if type(zOrNil) == "number" then P.view, P.z, P.scroll = "element", zOrNil, 0
  elseif not P.z then P.view = "table" end
end
function R.closePeriodic()
  P.open = false
  P.drag, P.dragBar = nil, nil
end

-- ================================================================ isotope filtering (per-element,
-- rebuilt only when the element or filter changes -- never a full 3,383-row scan; see G.filteredIsotopes)
local FILTER_CACHE = { z = nil, filter = nil, rows = nil }
local function isotopesFor(z, filter)
  if FILTER_CACHE.z == z and FILTER_CACHE.filter == filter then return FILTER_CACHE.rows end
  local data = P.data
  local el = data and data.byZ[z]
  local rows = {}
  if el then
    for _, iso in ipairs(el.isotopes) do
      local stability = iso[4]
      local promoted = iso[10]
      local keep
      if filter == "stable" then keep = (stability == "stable")
      elseif filter == "radioactive" then keep = (stability ~= "stable")
      elseif filter == "promoted" then keep = (promoted ~= false)
      elseif filter == "linked" then keep = (LINK[el.sym] ~= nil)
      else keep = true end
      if keep then rows[#rows + 1] = iso end
    end
  end
  FILTER_CACHE.z, FILTER_CACHE.filter, FILTER_CACHE.rows = z, filter, rows
  return rows
end

-- ================================================================ scrollbar (click-to-seek + drag,
-- identical contract to guide.lua's own drawScrollbar/scrollbarSeek pair)
local function drawScrollbar(x, y, h, total, vis, scroll, dragKey)
  if total <= vis then return nil end
  local maxScroll = math.max(0, total - vis)
  local thumbH = math.max(10, floor(h * vis / total))
  local avail = h - thumbH
  local thumbY = y + ((maxScroll > 0) and floor(avail * scroll / maxScroll) or 0)
  graphics.fillRect(x, y, SBW, h, 22, 22, 34, 220); graphics.drawRect(x, y, SBW, h, 60, 60, 80, 200)
  local dragging = (P.drag == dragKey)
  graphics.fillRect(x, thumbY, SBW, thumbH, dragging and 255 or 150, dragging and 220 or 150, dragging and 80 or 175, 255)
  return { track = { x, y, x + SBW, y + h }, thumbH = thumbH, maxScroll = maxScroll }
end
local function scrollbarSeek(bar, my)
  local avail = (bar.track[4] - bar.track[2]) - bar.thumbH
  local rel = my - bar.track[2] - bar.thumbH / 2
  local frac = (avail > 0) and (rel / avail) or 0
  frac = math.max(0, math.min(1, frac))
  return floor(frac * bar.maxScroll + 0.5)
end

-- ================================================================ draw: periodic table view
local CELL_W, CELL_H, CELL_GAP = 30, 26, 1
local function tableOrigin()
  return GX + 8, BY + 4
end
local function drawTableView(mx, my)
  local data = P.data
  P.cellRects = {}
  local ox, oy = tableOrigin()
  graphics.drawText(ox, BY - 12, "Click an element for its isotope chart. Coloured by family.",
    170, 170, 185, 255)
  for _, el in ipairs(data.elements) do
    local cx = ox + (el.grp - 1) * (CELL_W + CELL_GAP)
    local cy = oy + (el.row - 1) * (CELL_H + CELL_GAP) + (el.row >= 9 and 8 or 0) -- extra gap above footnote rows
    local r = { cx, cy, cx + CELL_W, cy + CELL_H, z = el.z }
    local hov = hitRect(r, mx, my)
    local fr, fg, fb = familyColour(el.family)
    local hasLink = LINK[el.sym] ~= nil
    graphics.fillRect(cx, cy, CELL_W, CELL_H, floor(fr * (hov and 0.55 or 0.35)), floor(fg * (hov and 0.55 or 0.35)), floor(fb * (hov and 0.55 or 0.35)), 255)
    graphics.drawRect(cx, cy, CELL_W, CELL_H, fr, fg, fb, hov and 255 or 180)
    graphics.drawText(cx + 3, cy + 2, tostring(el.z), 150, 150, 160, 255)
    graphics.drawText(cx + 3, cy + 11, el.sym, 240, 240, 245, 255)
    if hasLink then graphics.fillRect(cx + CELL_W - 6, cy + 2, 4, 4, 120, 255, 140, 255) end -- green dot: linked to a real material this game has
    P.cellRects[#P.cellRects + 1] = r
    if hov then
      graphics.fillRect(mx + 10, my + 4, textW(el.name) + 60, 26, 0, 0, 0, 235)
      graphics.drawRect(mx + 10, my + 4, textW(el.name) + 60, 26, 120, 124, 170, 255)
      graphics.drawText(mx + 14, my + 7, el.name:sub(1, 1):upper() .. el.name:sub(2) .. " (Z=" .. el.z .. ")", 230, 230, 235, 255)
      graphics.drawText(mx + 14, my + 18, hasLink and "In this world -- click for details" or (#el.isotopes .. " known isotopes"), hasLink and 150 or 190, hasLink and 255 or 190, hasLink and 170 or 200, 255)
    end
  end
  graphics.fillRect(ox, oy - 12, 8, 8, 120, 255, 140, 255)
  graphics.drawText(ox + 12, oy - 12, "= at least one isotope of this element is obtainable in your world (click it for how)", 170, 220, 175, 255)
end

-- ================================================================ draw: element / isotope-chart view
local ROW_H = 12
local FILTERS = { { id = "all", label = "ALL" }, { id = "stable", label = "STABLE" },
                   { id = "radioactive", label = "RADIOACTIVE" }, { id = "promoted", label = "PROMOTED" },
                   { id = "linked", label = "LINKED" } }
local function drawElementView(mx, my)
  local data = P.data
  local el = data.byZ[P.z]
  if not el then P.view = "table"; return end
  P.filterRects, P.linkRect = {}, nil
  graphics.drawText(GX + 6, BY - 12, string.format("%s (Z=%d) -- %s -- family: %s",
    el.name:sub(1, 1):upper() .. el.name:sub(2), el.z, el.sym, el.family), 255, 220, 80, 255)

  -- link line: does this element exist in this game, and how do you get it
  local link = LINK[el.sym]
  local ly = BY + 2
  if link then
    local haveA = R.has and R.has(link.code)
    local haveB = link.alt and R.has(link.alt)
    local have = haveA or haveB
    local codeTxt = link.alt and (link.code .. " / " .. link.alt) or link.code
    graphics.drawText(GX + 6, ly, (have and "IN THIS WORLD: " or "Recipe/vein exists, not registered this session: ") .. codeTxt .. " (" .. R.nice(link.code) .. ")",
      have and 140 or 220, have and 255 or 200, have and 160 or 120, 255)
    ly = ly + 11
    for _, line in ipairs({ link.note }) do
      -- wrap long notes at ~90 chars so they never run off the panel
      local remaining = line
      while #remaining > 0 do
        local cut = math.min(92, #remaining)
        if cut < #remaining then
          local sp = remaining:sub(1, cut):match(".*() ")
          if sp then cut = sp end
        end
        graphics.drawText(GX + 6, ly, remaining:sub(1, cut), 190, 195, 205, 255)
        remaining = remaining:sub(cut + 1):gsub("^%s+", "")
        ly = ly + 10
      end
    end
  else
    graphics.drawText(GX + 6, ly, "No known in-game material for this element yet.", 160, 160, 170, 255)
    ly = ly + 11
  end

  -- filter chips (mouse-only filtering, per accessibility requirement)
  local fx = GX + 6
  for _, f in ipairs(FILTERS) do
    local w = textW(f.label) + 8
    local r = { fx, ly + 4, fx + w, ly + 16, id = f.id }
    local active = (P.filter == f.id)
    local hov = hitRect(r, mx, my)
    graphics.fillRect(r[1], r[2], w, 12, active and 70 or (hov and 44 or 24), active and 74 or (hov and 48 or 26), active and 40 or (hov and 70 or 40), 255)
    graphics.drawRect(r[1], r[2], w, 12, active and 255 or 140, active and 220 or 140, active and 80 or 150, 255)
    graphics.drawText(r[1] + 4, r[2] + 2, f.label, active and 255 or 210, active and 220 or 210, active and 90 or 220, 255)
    P.filterRects[#P.filterRects + 1] = r
    fx = fx + w + 4
  end
  ly = ly + 20

  -- isotope table header
  local colX = { mass = GX + 6, ab = GX + 60, stab = GX + 116, half = GX + 190, decay = GX + 300, role = GX + 430 }
  graphics.fillRect(GX + 4, ly, GW - 8, 11, 40, 44, 80, 255)
  graphics.drawText(colX.mass, ly + 2, "MASS", 220, 220, 230, 255)
  graphics.drawText(colX.ab, ly + 2, "ABUND%", 220, 220, 230, 255)
  graphics.drawText(colX.stab, ly + 2, "STABILITY", 220, 220, 230, 255)
  graphics.drawText(colX.half, ly + 2, "HALF-LIFE", 220, 220, 230, 255)
  graphics.drawText(colX.decay, ly + 2, "DECAY", 220, 220, 230, 255)
  graphics.drawText(colX.role, ly + 2, "ROLE / GAME LINK", 220, 220, 230, 255)
  local listY0 = ly + 13
  local listAreaH = BOT - listY0
  local visRows = math.max(1, floor(listAreaH / ROW_H))

  local rows = isotopesFor(P.z, P.filter)
  P.scroll = math.max(0, math.min(P.scroll, math.max(0, #rows - visRows)))
  for i = 1, visRows do
    local iso = rows[i + P.scroll]
    if iso then
      local ry = listY0 + (i - 1) * ROW_H
      local A, massU, abund, stability, halfS, halfDisp, halfBand, decayStr, roleStr, promotedId =
        iso[1], iso[2], iso[3], iso[4], iso[5], iso[6], iso[7], iso[8], iso[9], iso[10]
      local sym = el.sym .. "-" .. A
      local rowBg = (i % 2 == 0) and { 18, 20, 32 } or { 14, 16, 26 }
      graphics.fillRect(GX + 4, ry, GW - 8, ROW_H - 1, rowBg[1], rowBg[2], rowBg[3], 220)
      graphics.drawText(colX.mass, ry + 1, sym, 235, 235, 240, 255)
      graphics.drawText(colX.ab, ry + 1, (abund and abund ~= false) and string.format("%.4g", abund) or "-", 200, 200, 210, 255)
      local stabCol = (stability == "stable") and { 150, 255, 160 } or (stability == "primordial") and { 220, 220, 140 } or { 255, 180, 140 }
      graphics.drawText(colX.stab, ry + 1, stability, stabCol[1], stabCol[2], stabCol[3], 255)
      graphics.drawText(colX.half, ry + 1, halfDisp, 210, 215, 230, 255) -- half_life_display used verbatim, per task brief
      graphics.drawText(colX.decay, ry + 1, decayStr == "" and "-" or decayStr, 200, 190, 220, 255)
      local roleTxt = roleStr == "" and "" or roleStr
      if promotedId and promotedId ~= false then
        roleTxt = (roleTxt ~= "" and (roleTxt .. " ") or "") .. "[ACCRETION: " .. promotedId .. "]"
      end
      graphics.drawText(colX.role, ry + 1, roleTxt == "" and "-" or roleTxt, 170, 220, 200, 255)
    end
  end
  P.listBar = drawScrollbar(GX + GW - SBW - 2, listY0, listAreaH, #rows, visRows, P.scroll, "list")
  graphics.drawText(GX + 6, BOT + 2, string.format("%d/%d isotopes shown", #rows, #el.isotopes), 150, 150, 160, 255)
end

-- ================================================================ input
hook(R.hooks.mousedown, function(x, y, button)
  if not P.open then
    if hitRect(TOGGLE, x, y) then R.openPeriodic(); return true end
    return
  end
  local B = P.btn or {}
  if hitRect(B.close, x, y) then R.closePeriodic(); return true end
  if P.view == "element" and hitRect(B.back, x, y) then P.view, P.scroll = "table", 0; return true end
  if P.view == "table" then
    for _, r in ipairs(P.cellRects or {}) do
      if hitRect(r, x, y) then P.view, P.z, P.scroll = "element", r.z, 0; return true end
    end
  elseif P.view == "element" then
    for _, r in ipairs(P.filterRects or {}) do
      if hitRect(r, x, y) then P.filter, P.scroll = r.id, 0; return true end
    end
    if P.listBar and hitRect(P.listBar.track, x, y) then
      P.scroll = scrollbarSeek(P.listBar, y); P.drag, P.dragBar = "list", P.listBar; return true
    end
  end
  return true -- swallow clicks inside the open panel so they never leak to world interaction underneath
end)
hook(R.hooks.mouseup, function() P.drag, P.dragBar = nil, nil end)
hook(R.hooks.tick, function()
  if P.open then R.uiPanelOpen = true end
  if P.open and P.drag and P.dragBar then P.scroll = scrollbarSeek(P.dragBar, R.mouse.y) end
end)
if R.hooks.wheel then
  hook(R.hooks.wheel, function(x, y, d)
    if not P.open or P.view ~= "element" then return end
    P.scroll = math.max(0, P.scroll - d)
    return true
  end)
end
hook(R.hooks.key, function(k)
  -- Escape is a CONVENIENCE, never the only path -- the on-screen X (B.close) does the same thing
  -- and is checked first in the mousedown hook above.
  if P.open and k == "escape" then R.closePeriodic(); return true end
end)

-- ================================================================ draw
hook(R.hooks.drawHUD, function()
  local mx, my = (R.mouse and R.mouse.x) or 0, (R.mouse and R.mouse.y) or 0
  if not P.open then
    -- Persistent, always-visible open button -- the accessibility fix this whole file exists to
    -- satisfy: no keybind required to ever find this feature. Hidden only while another big panel
    -- already owns the screen, matching guide.lua's own "only one panel at a time" convention.
    if R.guideOpen or R.menuOpen or R.titleScreen or (R.ui and R.ui.bagOpen) or (R.ui and R.ui.questOpen) or (R.ui and R.ui.controlsOpen) then return end
    local hov = hitRect(TOGGLE, mx, my)
    graphics.fillRect(TOGGLE[1], TOGGLE[2], TOGGLE[3] - TOGGLE[1], TOGGLE[4] - TOGGLE[2], hov and 44 or 22, hov and 48 or 24, hov and 70 or 40, 235)
    graphics.drawRect(TOGGLE[1], TOGGLE[2], TOGGLE[3] - TOGGLE[1], TOGGLE[4] - TOGGLE[2], hov and 255 or 150, hov and 230 or 160, hov and 140 or 110, 255)
    graphics.drawText(TOGGLE[1] + 4, TOGGLE[2] + 4, "ELEMENTS", hov and 255 or 210, hov and 235 or 220, hov and 190 or 230, 255)
    return
  end
  R.uiPanelOpen = true
  P.btn = P.btn or {}
  local B = P.btn
  graphics.fillRect(GX, GY, GW, GH, 12, 14, 28, 248)
  graphics.drawRect(GX, GY, GW, GH, 255, 220, 80, 255)
  graphics.fillRect(GX, GY, GW, 15, 40, 44, 80, 255)
  graphics.drawText(GX + 5, GY + 4, "PERIODIC TABLE", 255, 220, 80, 255)
  local data = P.data
  graphics.drawText(GX + 130, GY + 4, "source: " .. (data.citation or "?"), 150, 150, 165, 255)
  B.close = { GX + GW - 14, GY + 2, GX + GW - 2, GY + 13 }
  local closeHover = hitRect(B.close, mx, my)
  graphics.fillRect(B.close[1], B.close[2], 12, 11, closeHover and 150 or 60, closeHover and 60 or 40, closeHover and 60 or 44, 255)
  graphics.drawText(B.close[1] + 3, B.close[2] + 2, "X", 255, 210, 210, 255)
  if P.view == "element" then
    B.back = { GX + GW - 60, GY + 2, GX + GW - 16, GY + 13 }
    local backHover = hitRect(B.back, mx, my)
    graphics.fillRect(B.back[1], B.back[2], 44, 11, backHover and 90 or 44, backHover and 90 or 48, backHover and 60 or 70, 255)
    graphics.drawText(B.back[1] + 3, B.back[2] + 2, "< BACK", backHover and 255 or 210, backHover and 230 or 210, backHover and 140 or 220, 255)
  else
    B.back = nil
  end
  if P.view == "table" then drawTableView(mx, my) else drawElementView(mx, my) end
end)

hook(R.hooks.newworld, function() R.closePeriodic() end)
