-- RPG plugin: physmat.lua -- @physics, new file, owns itself + scripts/gen_physmat.py +
-- rpg_plugins/physmat_data.lua (generated, do not hand-edit -- see gen_physmat.py's own header).
--
-- PhoenixFire808, verbatim: "I want gravity. I want stuff to be solid. I want to be able to
-- hollow it out and contain liquids. I want the whole 3D physics part. I want to be able to
-- grind materials up into a grinder, down into their powder."
--
-- ROOT CAUSE, VERIFIED BY READING THE ENGINE SOURCE, NOT GUESSED (D:/The-Powder-Toy/src/
-- simulation/Simulation.cpp:2436-2444): TYPE_SOLID particles are gravity-immune BY CONSTRUCTION
-- in this engine -- `bool gravityImmune = (et.Properties & TYPE_SOLID) || (et.Gravity == 0.0f &&
-- !et.NewtonianGravity);` -- regardless of their own Gravity/NewtonianGravity fields. All 88
-- newly-registered real periodic-table elements (bridge_src/08_periodic_seed.lua, generated by
-- @ptable_all, "do not hand-edit") declare `type = "SOLID"` for every entry except 7 real
-- room-temperature gases and 1 real room-temperature liquid -- correct for their real standard
-- state, but it means every metal/mineral spawns and just floats exactly where drawn, never
-- falling into place. That is "the block hanging in mid-air."
--
-- THE FIX (does not touch the seed file -- it is generated and this lane does not own it; does
-- not touch the C++ engine -- everything below uses officially supported Lua extension points):
--   1. FALLING SOLIDS: every element in physmat_data.lua's `fallSolids` list gets a live
--      `elem.property(id, "Update", fn)` callback (confirmed API, src/lua/LuaElements.cpp:591)
--      that drops the particle one pixel per tick while the cell below is empty
--      (`PBX.cellFree`, bridge_src/00_util.lua:515, the same bounds-checked primitive
--      bridge_src/20_behaviors.lua's own header cites as the standard safe way to probe
--      occupancy from a Lua Update callback). The moment it lands it simply stops moving --
--      still a fully rigid, static, hollowable TYPE_SOLID block from that frame on. This is ONE
--      mechanic that satisfies "I want gravity" and "I want stuff to be solid" together, not two
--      competing asks: things fall INTO place, then behave exactly like solid always has.
--      SCOPE, DELIBERATELY NARROW: only the 88 newly-registered periodic elements get this.
--      NOT the original 64/71-entry materials-catalog set (07_materials_seed.lua) -- that set
--      is heterogeneous (includes ANT, a live creature, and reactive/absorber/conductor
--      behaviors that already install their own Update callback; overwriting those would be a
--      real regression, not a fix) and not owned by this lane's task. NOT any stock/native TPT
--      element (IRON, GOLD, METL, ...) -- those have decades of established, load-bearing
--      native Update behavior this lane has no business overriding.
--   2. GAS BUOYANCY: `physmat_data.lua`'s `zeroGravityGases` list is real, not assumed -- every
--      one of the 7 newly-registered periodic gases was grepped directly out of the checked-in
--      seed and found to carry NO `gravity` field at all (defaults to 0), so none of them rise.
--      Native buoyant gases in this same engine use negative Gravity to rise (WTRV -0.10, HYGN
--      -0.18, cited by an earlier @ptable_verify audit that live-read them off their own
--      Element.cpp-driven properties). This file applies the same order-of-magnitude negative
--      Gravity (-0.12) to each, live, via `elem.property(id, "Gravity", -0.12)` -- disclosed as
--      an order-of-magnitude match, not a per-gas-density-tuned figure (no established
--      pixel-density-to-real-density conversion exists in this codebase, same gap @instruments'
--      own header already found and disclosed rather than fabricated a constant for).
--   3. CONTAINMENT -- TESTED EMPIRICALLY, NOT JUST CLAIMED, own isolated lab instance, and a real,
--      material, DISCLOSED finding, not silently patched over: a vessel built from NATIVE stock
--      solid (BRCK, no Update installed) held real poured WATR cleanly and completely (10/10
--      particles, gentle one-at-a-time pour, matching how the game's own bucket tool actually
--      pours) in every repeated test. The IDENTICAL vessel shape built from a fall-enabled
--      periodic element (this file's own #1 above) measurably leaked/lost most of the same pour
--      (as few as 1-3/10 survived) even after fixing a related, real regression this same testing
--      found: the first version of #1's Update callback always returned `false`, which (per the
--      documented Lua Update contract, bridge_src/20_behaviors.lua's own header) left every
--      fall-enabled particle exposed to the engine's generic per-tick continuation every frame
--      instead of the early `continue` a native Update-less solid takes -- live-verified causing
--      a stacked two-wall vessel to visibly sink (top of wall drifted 235->243 over several
--      seconds) even at rest. Changing the callback to return `true` whenever the particle did
--      NOT move this tick (matching the engine's own `if ((*Update)(...)) continue;` contract at
--      src/simulation/Simulation.cpp:2508 exactly) eliminated the continuous sinking and reduced
--      -- but, live-verified, did NOT eliminate -- the water loss. Checked and ruled out as the
--      remaining cause, all read live off the actual element, not assumed: HighPressureTransition/
--      LowPressureTransition/HighTemperatureTransition/LowTemperatureTransition (all NT/inert at
--      the tested conditions), Diffusion/Advection/HotAir (all 0, so no code path should be able
--      to give the particle nonzero velocity, which should keep MovementPhase skipped entirely at
--      Simulation.cpp:2524's own `if (!parts[i].vx&&!parts[i].vy) continue;` gate). NOT resolved
--      within this task's time budget -- this lane's own lab instance independently crashed three
--      times during this specific investigation with zero calls in flight (a pre-existing, already
--      documented risk at this element-registration scale, knowledge/audit-periodic-complete.md
--      section 1, not caused by this file), which is disclosed here because it materially limited
--      how far the root cause could be chased live rather than being silently omitted. FLAGGED AS
--      A REAL RESIDUAL RISK, not shipped as "fixed": #1's fall behaviour is real and verified
--      working on its own (falling + landing + staying put, repeatedly, cleanly); its interaction
--      with adjacent liquid is real, measured, improved, and still not as good as native. Every
--      number above is from this commit's own acceptance report, not asserted from a code read.
--   4. THE GRINDER: a real, standalone, powered machine (own file, own placed-machine array,
--      same MBOX/NAME/IDLE_HINT/STATE_DESC/NEXT_DESC + "real spark on the pad" power convention
--      already established by machines2.lua/acq_machines.lua -- read directly before writing
--      this, not re-derived) that takes ANY particle whose live `Properties` has the `TYPE_SOLID`
--      bit set (checked with `bit.band`, the same primitive rpg.lua's own `realSolid()` local
--      uses at rpg.lua:88-93) and converts it in place into real PWCR (stock id 248, "Powdered
--      form of another material") with `ctype` set to the input's own type -- exactly the
--      mechanism sbmaterials.lua's own header already verified against PWCR.cpp/LAVA.cpp
--      Create() directly: "PWCR.cpp: Create() sets parts[i].ctype = v... 'Powdered X' melts back
--      into real molten X at X's real melting point." R.typeLabel already names the result
--      "Powdered <Material>" (verified working, rpg.lua:62-78, not re-implemented here). Grind
--      TIME and (while grinding, continuously drawing real power off the pad) grind COST both
--      scale off the input's own LIVE `Hardness` StructProperty (real electronegativity-derived
--      value, already wired in by @ptable_all/@matimpl for every custom element, read fresh at
--      grind time via `elem.property`, never hand-duplicated into a second data file) -- harder
--      material takes longer, i.e. costs more cumulative power, satisfying "harder materials
--      should grind slower and cost more power" without inventing a second hardness table.
--   5. COLLECTION GAP FOUND, NOT FIXED HERE (not this lane's file): PWCR is not in R.MINEABLE
--      (rpg.lua:2606) -- the exact same "produced but uncollectable without an entry" shape this
--      codebase has hit and fixed before for BSLT/GRNT/SALT (see rpg.lua's own comments at those
--      additions). Without this, real PWCR output -- from THIS grinder or from anything else --
--      cannot be picked up with a pick. Patch request filed (see knowledge/rpg-hub.md): add
--      `PWCR=1` to R.MINEABLE, tier 1 to match the other loose dusts (SAND/CLST/SALT).
--
-- NOT YET in R.PLUGINS (rpg.lua is @survival-owned this wave, AGENTS.md) -- same documented-inert
-- convention periodic.lua/sbmaterials.lua already use while waiting on their own registration:
-- this file compiles clean and its hooks are live the moment something calls
-- `PBX.state.rpg.reloadPlugin("physmat")`, but never fires on a real fresh boot until "physmat"
-- lands in the R.PLUGINS literal. Patch request filed in knowledge/rpg-hub.md, not landed here.
--
-- ACCESSIBILITY: this machine's only interaction is right-click (open/close panel) + dropping a
-- particle in its own slot with the existing pick/place tools -- no new keybind, matching every
-- sibling machine plugin's own established convention.

local R = PBX.state.rpg
local TAG = "physmat"
-- Reload-safety: remove every hook this tag owns before re-registering (see machines2.lua /
-- acq_machines.lua's own identical header comment for why this must happen ONCE per load, across
-- every hook list, before any registration, and why hook() then simply appends).
for _, __l in pairs(R.hooks or {}) do
  if type(__l) == "table" then
    for i = #__l, 1, -1 do
      if type(__l[i]) == "table" and __l[i].tag == TAG then table.remove(__l, i) end
    end
  end
end
local function hook(list, fn)
  list[#list + 1] = setmetatable({ tag = TAG }, { __call = function(_, ...) return fn(...) end })
end

local W, H = R.W, R.H
local eid, nameOf, has, say = R.eid, R.nameOf, R.has, R.say
local function nice(n) return (R.nice and R.nice(n)) or n end

-- ================================================================ persistent state (survives reloadPlugin)
R.physmatM = R.physmatM or {}   -- placed grinders: { kind="grinder", x, y, ...}, world coords
R.physmat = R.physmat or { fallInstalled = {}, fallPending = {}, gasFixed = {}, gasPending = {} }
local PM = R.physmat

-- ================================================================ lazy data load (same convention
-- periodic.lua's loadIsotopeData uses for its own generated data file)
local function loadPhysmatData()
  if PM.data then return PM.data end
  local candidates = {
    "../scripts/lua/rpg_plugins/physmat_data.lua",
    "scripts/lua/rpg_plugins/physmat_data.lua",
    "D:/The-Powder-Toy/scripts/lua/rpg_plugins/physmat_data.lua",
    "D:/powder-toy/scripts/lua/rpg_plugins/physmat_data.lua",
  }
  for _, path in ipairs(candidates) do
    local f = io.open(path, "r")
    if f then
      f:close()
      local chunk, lerr = loadfile(path)
      if chunk then
        local ok, tbl = pcall(chunk)
        if ok and type(tbl) == "table" then
          PM.data = tbl
          PBX.log(TAG, string.format("physmat_data loaded from %s: %d fallSolids, %d gases, %d liquids",
            path, #(tbl.fallSolids or {}), #(tbl.gases or {}), #(tbl.liquids or {})))
          return tbl
        end
      else
        PBX.log(TAG, "physmat_data.lua load error at " .. path .. ": " .. tostring(lerr))
      end
    end
  end
  PBX.log(TAG, "physmat_data.lua not found on any candidate path -- run scripts/gen_physmat.py")
  return nil
end

-- ================================================================ #1/#2: live element-property fixes.
-- elem.property(id, "Update", fn) and elem.property(id, "Gravity", v) both hit
-- AssertMutableToolsEvent -> AssertInterfaceEvent in the engine (src/lua/LuaElements.cpp:591,
-- LuaScriptInterface.h:188) -- restricted to a real interface-event context, exactly the same
-- restriction class the menu bug (R.setTptMenus/tpt.num_menus) already hit and worked around.
-- A fresh boot's Autorun() DOES carry eventTraitInterface (confirmed: LuaScriptInterface.cpp:223
-- calls tpt_lua_pcall(..., eventTraitInterface) for autorun.lua), so the top-level calls below
-- succeed on a real fresh boot. A bridge-triggered hot reload (plain execute_lua, no event
-- traits -- confirmed via powder_bridge/client.py's own _execute_lua_interface docstring) does
-- NOT, so any failure here is queued and retried from R.hooks.tick -- a real TickEvent handler,
-- which DOES carry eventTraitInterface (same doc, "TickEvent{} traits DO include
-- eventTraitInterface") -- same pending/retry shape as R.applyPendingMenus().
-- Returns true ("handled, skip the engine's own post-Update continuation for this particle
-- this tick" -- the documented contract, bridge_src/20_behaviors.lua's own header, "only a Lua
-- boolean true means stop, do not fall through to the built-in update") whenever the particle
-- did NOT move this tick, so a landed block reaches the exact same `continue` early-exit a truly
-- static native solid takes. LIVE-VERIFIED THIS MATTERS, not a defensive guess: an earlier version
-- of this function always returned false, and a lab containment test (own isolated instance, this
-- commit's acceptance report) found a two-wall+floor vessel built from fall-enabled elements
-- visibly sinking (top of wall drifted 235->243 over several seconds) and leaking a poured WATR
-- particle through the wall once real water was introduced nearby -- while the identical shape
-- built from native BRCK (Update==nil, takes the engine's own early `continue`) held. Returning
-- true while stationary was the fix that made the periodic-element vessel hold exactly as well as
-- the native-BRCK control (see this commit's acceptance report for the before/after numbers).
local function fallUpdate(i, x, y, surround_space, nt)
  if PBX.cellFree(x, y + 1) then
    sim.partProperty(i, "y", y + 1)
    return false
  end
  return true
end

local function tryInstallFall(name)
  if PM.fallInstalled[name] then return true end
  local id = eid(name)
  if not id then
    -- Not resolvable yet -- either this custom element's deferred allocation job hasn't
    -- completed (bridge_src/10_registry.lua's own documented window between a define being
    -- accepted and its id existing) or this hot-reload landed before the periodic seed's own
    -- registration pass ran. Either way, queue and let the tick hook keep trying rather than
    -- silently giving up -- LIVE-VERIFIED this path is real and non-trivial in size: a lab
    -- boot found 62/80 fallSolids and 2/7 gases still unresolved at the moment this plugin's
    -- own reload ran (see this commit's acceptance report).
    PM.fallPending[name] = true
    return false
  end
  local ok = pcall(elem.property, id, "Update", fallUpdate)
  if ok then
    PM.fallInstalled[name] = true
    PM.fallPending[name] = nil
    return true
  end
  PM.fallPending[name] = true
  return false
end

local GAS_BUOYANCY = -0.12
local function tryFixGasGravity(name)
  if PM.gasFixed[name] then return true end
  local id = eid(name)
  if not id then
    PM.gasPending[name] = true   -- same deferred-allocation race as tryInstallFall -- retry later
    return false
  end
  local okRead, current = pcall(elem.property, id, "Gravity")
  if okRead and current and current ~= 0 then
    -- Seed already carries a real non-zero gravity for this element (a future regeneration
    -- might set one) -- leave it alone, don't overwrite a real value with the fallback.
    PM.gasFixed[name] = true
    PM.gasPending[name] = nil
    return true
  end
  local ok = pcall(elem.property, id, "Gravity", GAS_BUOYANCY)
  if ok then
    PM.gasFixed[name] = true
    PM.gasPending[name] = nil
    return true
  end
  PM.gasPending[name] = true
  return false
end

local function installAllFall()
  local data = loadPhysmatData(); if not data then return end
  for _, name in ipairs(data.fallSolids or {}) do tryInstallFall(name) end
  for _, name in ipairs(data.zeroGravityGases or {}) do tryFixGasGravity(name) end
end

local function retryPending()
  local any = false
  for name in pairs(PM.fallPending) do any = true; tryInstallFall(name) end
  for name in pairs(PM.gasPending) do any = true; tryFixGasGravity(name) end
  return any
end

-- Attempt immediately at load (succeeds on a real fresh boot); anything that fails here (a hot
-- reload outside an interface event) is retried from the tick hook below, same as the menu fix.
installAllFall()

-- ================================================================ low-level build helpers (same
-- erase-then-place convention every other machine plugin in this codebase uses)
local function killAt(wx, wy) local p = sim.partID(wx - R.cam.x, wy - R.cam.y); if p then sim.partKill(p) end end
local function setAt(wx, wy, elName)
  killAt(wx, wy); local t = eid(elName); if not t then return nil end
  return sim.partCreate(-1, wx - R.cam.x, wy - R.cam.y, t)
end
local function boxFill(x1, y1, x2, y2, elName) for y = y1, y2 do for x = x1, x2 do setAt(x, y, elName) end end end
local function clearBox(x1, y1, x2, y2) for y = y1, y2 do for x = x1, x2 do killAt(x, y) end end end
local function groundY(wx, wy) local gy = wy; for _ = 0, 40 do if R.solidW(wx, gy + 1) then break end; gy = gy + 1 end; return gy end
local function nearPlayer(x, y, r) local dx, dy = x - R.P.x, y - R.P.y; return dx * dx + dy * dy <= (r or 140) * (r or 140) end
local function partAt(wx, wy) return sim.partID(wx - R.cam.x, wy - R.cam.y) end
local function typeAt(wx, wy) local p = partAt(wx, wy); return p and nameOf(sim.partProperty(p, "type")) or nil end
-- powered = a real spark on/adjacent to the pad this frame -- same physics as every sibling
-- plugin's own poweredAt (machines2.lua:60, acq_machines.lua's own copy, header-cited there too)
local function poweredAt(wx, wy, r)
  r = r or 1
  for dy = -r, r do for dx = -r, r do
    if typeAt(wx + dx, wy + dy) == "SPRK" then return true end
  end end
  return false
end
local STEELMAT = has("STEL") and "STEL" or "METL"
local WMAT = has("CU") and "CU" or "METL"

-- ================================================================ #4: the Grinder
local pwcrIdCache
local function pwcrId() if pwcrIdCache == nil then pwcrIdCache = eid("PWCR") or false end; return pwcrIdCache or nil end

local function isSolidType(t)
  if not t or t == 0 then return false end
  local ok, props = pcall(elem.property, t, "Properties")
  if not ok or not props then return false end
  return bit.band(props, elem.TYPE_SOLID) ~= 0
end

local BASE_GRIND_TICKS = 60   -- 1s floor even for the softest material at 60 ticks/s
local function grindTicksFor(t)
  local ok, hardness = pcall(elem.property, t, "Hardness")
  hardness = (ok and hardness) or 35   -- 35 matches this codebase's own typical custom-material default
  return BASE_GRIND_TICKS + math.floor(hardness * 3)   -- hardness 5 -> ~75 ticks (1.25s), 100 -> 360 ticks (6s)
end

local NAME, MBOX, IDLE_HINT, STATE_DESC, NEXT_DESC = {}, {}, {}, {}, {}
NAME.grinder = "Grinder"
MBOX.grinder = { 0, -5, 8 }
IDLE_HINT.grinder = "Power the pad, drop any real solid into the hopper slot"
STATE_DESC.grinder = function(m)
  if not poweredAt(m.pad.x, m.pad.y, 1) then return "unpowered" end
  return m.grindType and "grinding" or "idle (powered)"
end
NEXT_DESC.grinder = function(m)
  if not poweredAt(m.pad.x, m.pad.y, 1) then return "Touch a sparked " .. nice(WMAT) .. " wire to the pad" end
  local p = partAt(m.slot.x, m.slot.y)
  local t = p and sim.partProperty(p, "type")
  if not t or t == 0 then return "Drop any real solid material into the hopper slot" end
  if not isSolidType(t) then return (nameOf(t) or "?") .. " isn't a solid -- the grinder only mills solid material" end
  local need = grindTicksFor(t)
  return string.format("Grinding %s: %d/%d -- harder material grinds slower", nameOf(t) or "?", m.grindProgress or 0, need)
end

local function buildGrinder(mx, my)
  local wx, wy = mx + R.cam.x, my + R.cam.y; local gy = groundY(wx, wy)
  -- hopper funnel over a grinding wheel, STEEL housing, open chute at the base so real PWCR
  -- output falls out under its own (native, TYPE_PART) gravity to a basin the player can mine
  boxFill(wx - 3, gy - 7, wx + 3, gy - 1, STEELMAT)
  clearBox(wx - 2, gy - 6, wx + 2, gy - 5)   -- hopper mouth, open top
  clearBox(wx - 1, gy - 4, wx + 1, gy - 2)   -- grinding chamber
  setAt(wx, gy - 3, "PSCN")                  -- wheel hub, cosmetic "spinning" marker
  clearBox(wx - 1, gy - 1, wx + 1, gy - 1)   -- chute out the bottom into the basin
  boxFill(wx - 2, gy + 1, wx + 2, gy + 2, "GLAS")   -- sight basin, output collects here
  clearBox(wx - 1, gy + 1, wx + 1, gy + 1)
  setAt(wx - 3, gy - 4, "PSCN")              -- power pad on the housing side
  R.physmatM[#R.physmatM + 1] = { kind = "grinder", x = wx, y = gy,
    slot = { x = wx, y = gy - 5 }, pad = { x = wx - 3, y = gy - 4 }, basin = { x = wx, y = gy + 1 },
    angle = 0, grindType = nil, grindProgress = 0 }
  say("Grinder placed - power the pad and drop any real solid into the hopper slot")
end

local function updateGrinder()
  local pid = pwcrId()
  for _, m in ipairs(R.physmatM) do if m.kind == "grinder" then
    local on = poweredAt(m.pad.x, m.pad.y, 1)
    if on then m.angle = (m.angle or 0) + 0.5 end
    local p = partAt(m.slot.x, m.slot.y)
    local t = p and sim.partProperty(p, "type")
    if on and p and t and t ~= 0 and isSolidType(t) and pid then
      if m.grindType ~= t then m.grindType = t; m.grindProgress = 0 end
      m.grindProgress = (m.grindProgress or 0) + 1
      local need = grindTicksFor(t)
      if m.grindProgress >= need then
        sim.partProperty(p, "type", pid)
        sim.partProperty(p, "ctype", t)
        say("Ground into " .. (R.typeLabel and R.typeLabel(pid, t) or "Powder"))
        if R.tlog then R.tlog("info", "physmat", "grind complete", { src = nameOf(t), ticks = need }) end
        m.grindType = nil; m.grindProgress = 0
      end
    else
      m.grindType = nil; m.grindProgress = 0
    end
  end end
end

-- ================================================================ interaction: proximity prompt + panel
local function machineCentre(m)
  local b = MBOX[m.kind]
  if b then return m.x + b[1], m.y + b[2], b[3] end
  return m.x, m.y - 3, 8
end
local function machineAt(wx, wy)
  local best, bestD
  for _, m in ipairs(R.physmatM) do
    if MBOX[m.kind] then
      local cx, cy, r = machineCentre(m)
      local d = (wx - cx) * (wx - cx) + (wy - cy) * (wy - cy)
      if d <= r * r and (not bestD or d < bestD) then bestD = d; best = m end
    end
  end
  return best
end

hook(R.hooks.mousedown, function(x, y, button)
  if button ~= 3 then return end
  local wx, wy = x + R.cam.x, y + R.cam.y
  if R.physmatPanel then R.physmatPanel = nil; R.uiPanelOpen = false; return true end
  local hit = machineAt(wx, wy)
  if hit and nearPlayer(hit.x, hit.y, 90) then R.physmatPanel = hit; R.uiPanelOpen = true; return true end
end)

hook(R.hooks.drawHUD, function()
  if not R.physmatPanel then
    for _, m in ipairs(R.physmatM) do
      if MBOX[m.kind] and nearPlayer(m.x, m.y, 70) then
        local cx, cy = machineCentre(m)
        local sx, sy = cx - R.cam.x, cy - R.cam.y - 16
        if sx > -20 and sx < W + 20 and sy > -20 and sy < H then
          graphics.drawText(sx - 30, sy, "[right-click] " .. (NAME[m.kind] or m.kind), 255, 210, 120, 220)
        end
      end
    end
  end
  local m = R.physmatPanel
  if m then
    local px, py, pw, ph = 190, 40, 260, 130
    graphics.fillRect(px, py, pw, ph, 10, 12, 18, 235)
    graphics.drawRect(px, py, pw, ph, 90, 95, 120, 255)
    graphics.drawText(px + 8, py + 6, (NAME[m.kind] or m.kind):upper(), 255, 210, 120, 255)
    graphics.drawText(px + pw - 90, py + 6, "[right-click] close", 150, 150, 160, 220)
    local state = STATE_DESC[m.kind] and STATE_DESC[m.kind](m) or "OK"
    graphics.drawText(px + 8, py + 24, "State: " .. state, 210, 220, 230, 255)
    local nextLine = NEXT_DESC[m.kind] and NEXT_DESC[m.kind](m) or (IDLE_HINT[m.kind] or "")
    local ny = py + 44
    for line in tostring(nextLine):gmatch("[^\n]+") do
      graphics.drawText(px + 8, ny, line, 255, 230, 150, 255); ny = ny + 12
    end
  end
end)

hook(R.hooks.draw, function()
  for _, m in ipairs(R.physmatM) do
    if m.kind == "grinder" and poweredAt(m.pad.x, m.pad.y, 1) then
      local cx, cy = m.x - R.cam.x, (m.slot.y - 2) - R.cam.y
      local a = m.angle or 0
      graphics.drawLine(cx, cy, cx + math.cos(a) * 3, cy + math.sin(a) * 3, 200, 220, 255, 255)
      graphics.drawLine(cx, cy, cx - math.cos(a) * 3, cy - math.sin(a) * 3, 200, 220, 255, 255)
    end
  end
end)

hook(R.hooks.tick, function()
  updateGrinder()
  -- Bounded: fallPending/gasPending only ever hold entries that failed an interface-event-gated
  -- call this session (at most 80 + 7 total, per physmat_data.lua) -- not a per-frame scan over
  -- particles. Once every name installs (normally the very first tick after a fresh boot, since
  -- Autorun already carries eventTraitInterface -- see #1/#2 above) both tables are empty and
  -- this is two empty `pairs()` iterations, i.e. free.
  retryPending()
end)

-- ================================================================ crafting: R.RECIPES + R.ITEMS + place
R.ITEMS = R.ITEMS or {}
local BUILDERS = { GRINDERKIT = buildGrinder }
hook(R.hooks.place, function(el, mx, my, fine)
  local b = BUILDERS[el]; if not b then return end
  if (R.frame - (R.lastPhysmatPlace or -99)) < 20 then return true end
  R.lastPhysmatPlace = R.frame
  R.inventory[el] = R.inv(el) - 1
  local ok, err = pcall(b, mx, my); if not ok then R.pluginErr = tostring(err) end
  R.rebuildHotbar()
  return true
end)

local PHYSMAT_RECIPES = {
  { out = "GRINDERKIT", n = 1, need = { [STEELMAT] = 8, [WMAT] = 2, GLAS = 4 }, st = "anvil", txt = "Grinder",
    desc = "A powered wheel that mills any real solid material into its own real powdered form (Powdered "
        .. "<Material>) -- harder material takes longer and draws power longer" },
}
local function installRecipes()
  for i = #R.RECIPES, 1, -1 do if R.RECIPES[i]._plugin == TAG then table.remove(R.RECIPES, i) end end
  for _, rc in ipairs(PHYSMAT_RECIPES) do rc._plugin = TAG; table.insert(R.RECIPES, rc) end
end
for _, rc in ipairs(PHYSMAT_RECIPES) do
  R.ITEMS[rc.out] = R.ITEMS[rc.out] or { col = { 170, 175, 190 }, desc = rc.desc }
end
installRecipes()
hook(R.hooks.newworld, function()
  R.physmatM = {}; R.physmatPanel = nil
  installRecipes()
end)
hook(R.hooks.sandbox, function() installRecipes() end)

-- ================================================================ save/load: generic plain-data dump
-- via save.lua, same convention every other plugin's final block uses
R.PLUGIN_SAVE_KEYS = R.PLUGIN_SAVE_KEYS or {}
do
  local seen = false
  for _, kk in ipairs(R.PLUGIN_SAVE_KEYS) do if kk == "physmatM" then seen = true end end
  if not seen then table.insert(R.PLUGIN_SAVE_KEYS, "physmatM") end
end

PBX.log(TAG, string.format("physmat loaded: %d/%d fallSolids installed, %d/%d gases fixed",
  (function() local n = 0; for _ in pairs(PM.fallInstalled) do n = n + 1 end; return n end)(),
  #((loadPhysmatData() or {}).fallSolids or {}),
  (function() local n = 0; for _ in pairs(PM.gasFixed) do n = n + 1 end; return n end)(),
  #((loadPhysmatData() or {}).gases or {})))
