-- physmat_data.lua -- GENERATED by scripts/gen_physmat.py. Do not hand-edit.
-- Source: D:/powder-toy/bridge_src/08_periodic_seed.lua (88 entries parsed, all 88 expected as of 2026-09-0X).
-- Regenerate: `python scripts/gen_physmat.py` after 08_periodic_seed.lua changes shape.
-- fallSolids: every periodic-seed entry declared type=SOLID -- gets a live 'falls until
--   landed' Update callback from physmat.lua (see that file's own header for why).
-- gases/liquids: containment + (for gases) buoyancy targets physmat.lua verifies/fixes live.
-- zeroGravityGases: the subset of `gases` this script found with NO gravity field (or an
--   explicit 0) in the checked-in seed at generation time -- physmat.lua applies a real
--   negative Gravity to these specifically, live, rather than to every gas unconditionally,
--   so a future seed revision that already sets a real per-gas buoyancy value is left alone.
return {
  fallSolids = { "AC", "AG", "AM", "AS", "AT", "B", "BA", "BH", "BI", "BK", "C", "CA", "CE", "CF", "CM", "CN", "CS", "DB", "DS", "DY", "ER", "ES", "EU", "FL", "FM", "FR", "GA", "GE", "HF", "HO", "HS", "I", "IN", "IR", "K", "LA", "LR", "LV", "MC", "MD", "MN", "MO", "MT", "NB", "ND", "NH", "NI", "NO", "NP", "OS", "PA", "PD", "PR", "RA", "RE", "RF", "RG", "RH", "RU", "S", "SB", "SC", "SE", "SG", "SM", "SN", "SR", "TA", "TB", "TC", "TE", "TH", "TL", "TM", "TS", "V", "Y", "YB", "ZN", "ZR" },
  gases = { "AR", "F", "HE", "KR", "NE", "OG", "XE" },
  liquids = { "BR" },
  zeroGravityGases = { "AR", "F", "HE", "KR", "NE", "OG", "XE" },
}
