"""Generate scripts/lua/rpg_plugins/physmat_data.lua from the checked-in periodic-table seed.

WHY THIS EXISTS (@physics, 2026-09-0X): PhoenixFire808, verbatim: "I want gravity. I want stuff
to be solid... I want the whole 3D physics part. I want to be able to grind materials up into a
grinder, down into their powder." Root cause of the "gravity" half, verified against the engine
source directly (D:/The-Powder-Toy/src/simulation/Simulation.cpp:2444, comment block at
2436-2444): `TYPE_SOLID` particles are gravity-immune BY CONSTRUCTION in this engine, regardless
of their own Gravity/NewtonianGravity fields -- `bool gravityImmune = (et.Properties &
TYPE_SOLID) || ...`. All 88 newly-registered real periodic-table elements
(bridge_src/08_periodic_seed.lua, GENERATED by @ptable_all, "do not hand-edit") declare
`type = "SOLID"` for every entry except 7 real room-temperature gases and 1 real room-temperature
liquid (Br) -- correct for their real standard state, but it means every metal/mineral spawns as
an immobile block that floats exactly where it was drawn, "hanging in mid-air", never falling
into place the way a real dropped rock or ingot would.

THE FIX THIS FILE FEEDS (installed live by rpg_plugins/physmat.lua, NOT by hand-editing the seed
-- that file's own header already flags REGENERATION-BROKEN, i.e. no working generator exists for
it in either tree, so hand-editing it would make an already-fragile situation worse):
  - physmat.lua installs a per-element `Update` callback (the officially supported
    `elem.property(id, "Update", fn)` extension point, confirmed at
    src/lua/LuaElements.cpp:591-609) on every element in this file's `fallSolids` list: while the
    cell directly below is empty, the particle drops one pixel per tick; the moment it lands on
    another particle or the world floor it simply stops calling PBX.cellFree -- still a fully
    rigid, static, hollowable TYPE_SOLID block from that frame on, satisfying "I want stuff to be
    solid" and "I want gravity" as the same mechanic, not two competing ones.
  - physmat.lua also live-corrects buoyancy on this file's `gases` list: read directly off the
    live 08_periodic_seed.lua text (grep, not guessed), NONE of the 7 newly-registered periodic
    gases carry a `gravity` field at all, so they default to 0 -- no upward drift, failing "gases
    must rise". Native buoyant gases already in this engine use negative Gravity (WTRV -0.10,
    HYGN -0.18, live-read from their own Element.cpp-driven properties by an earlier audit this
    file's header cites). physmat.lua applies the same order-of-magnitude negative Gravity to any
    gas in this list still reading 0 live, not a per-gas-density-tuned value (disclosed, not
    fabricated as precise physics).
This file does NOT touch bridge_src/08_periodic_seed.lua, rpg.lua, or any other lane's file --
it only reads the checked-in seed (a public, already-generated artifact) and emits a brand new,
lazily-loaded data file this lane owns outright, same convention scripts/gen_isotope_data.py
established for periodic_data.lua.

Usage
-----
    python scripts/gen_physmat.py                # regenerate from the checked-in seed
    python scripts/gen_physmat.py --check         # verify the checked-in data file is fresh
    python scripts/gen_physmat.py --seed PATH     # use a different seed file (testing only)

Source of truth: bridge_src/08_periodic_seed.lua (both trees are expected byte-identical; this
script reads D:/powder-toy's copy, which is where this lane does its editing per AGENTS.md).
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path("D:/powder-toy")
DEFAULT_SEED = ROOT / "bridge_src" / "08_periodic_seed.lua"
OUT_PATH = ROOT / "scripts" / "lua" / "rpg_plugins" / "physmat_data.lua"

# One `add({ ... })` call per line in the seed file (verified 2026-09-0X: 88/88 lines matched this
# shape, `grep -c "^add("` == 88, zero unparsed lines) -- name and type are always both present as
# quoted string literals; gravity is present only on entries that already override the default (a
# handful of the 71-entry materials-catalog reuses do; none of the periodic-seed's own 7 gas rows
# do, per this script's own live grep at the time this docstring was written).
ADD_RE = re.compile(r'^add\(\{\s*name\s*=\s*"([A-Za-z0-9]+)".*?\}\)\s*$')
TYPE_RE = re.compile(r'type\s*=\s*"([A-Z]+)"')
GRAVITY_RE = re.compile(r'gravity\s*=\s*(-?[0-9.]+)')


def parse_seed(path: Path) -> list[dict]:
    rows = []
    for lineno, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        m = ADD_RE.match(line)
        if not m:
            continue
        name = m.group(1)
        tm = TYPE_RE.search(line)
        if not tm:
            raise SystemExit(f"{path}:{lineno}: add({{name={name!r}...}}) has no type= field -- seed shape changed, fix ADD_RE/TYPE_RE before trusting output")
        gm = GRAVITY_RE.search(line)
        rows.append({
            "name": name,
            "type": tm.group(1),
            "gravity": float(gm.group(1)) if gm else None,
            "line": lineno,
        })
    return rows


def classify(rows: list[dict]) -> dict[str, list[str]]:
    fall_solids = sorted(r["name"] for r in rows if r["type"] == "SOLID")
    gases = sorted(r["name"] for r in rows if r["type"] == "GAS")
    liquids = sorted(r["name"] for r in rows if r["type"] == "LIQUID")
    return {"fallSolids": fall_solids, "gases": gases, "liquids": liquids}


def render(seed_path: Path, rows: list[dict], classes: dict[str, list[str]]) -> str:
    def lua_list(names: list[str]) -> str:
        if not names:
            return "{}"
        return "{ " + ", ".join(f'"{n}"' for n in names) + " }"

    zero_gravity_gases = sorted(r["name"] for r in rows if r["type"] == "GAS" and (r["gravity"] is None or r["gravity"] == 0))
    lines = [
        "-- physmat_data.lua -- GENERATED by scripts/gen_physmat.py. Do not hand-edit.",
        f"-- Source: {seed_path.as_posix()} ({len(rows)} entries parsed, all 88 expected as of 2026-09-0X).",
        "-- Regenerate: `python scripts/gen_physmat.py` after 08_periodic_seed.lua changes shape.",
        "-- fallSolids: every periodic-seed entry declared type=SOLID -- gets a live 'falls until",
        "--   landed' Update callback from physmat.lua (see that file's own header for why).",
        "-- gases/liquids: containment + (for gases) buoyancy targets physmat.lua verifies/fixes live.",
        "-- zeroGravityGases: the subset of `gases` this script found with NO gravity field (or an",
        "--   explicit 0) in the checked-in seed at generation time -- physmat.lua applies a real",
        "--   negative Gravity to these specifically, live, rather than to every gas unconditionally,",
        "--   so a future seed revision that already sets a real per-gas buoyancy value is left alone.",
        "return {",
        f'  fallSolids = {lua_list(classes["fallSolids"])},',
        f'  gases = {lua_list(classes["gases"])},',
        f'  liquids = {lua_list(classes["liquids"])},',
        f'  zeroGravityGases = {lua_list(zero_gravity_gases)},',
        "}",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--seed", type=Path, default=DEFAULT_SEED)
    ap.add_argument("--out", type=Path, default=OUT_PATH)
    ap.add_argument("--check", action="store_true", help="exit 1 if the checked-in output would change")
    args = ap.parse_args(argv)

    if not args.seed.exists():
        print(f"seed not found: {args.seed}", file=sys.stderr)
        return 2
    rows = parse_seed(args.seed)
    if not rows:
        print(f"parsed 0 add({{...}}) rows out of {args.seed} -- seed shape changed, ADD_RE needs updating before this script can be trusted", file=sys.stderr)
        return 2
    classes = classify(rows)
    text = render(args.seed, rows, classes)

    if args.check:
        current = args.out.read_text(encoding="utf-8") if args.out.exists() else None
        # ignore the source line's row-count comment when comparing so a re-run against an
        # unchanged seed with a different docstring date doesn't false-fail
        def strip_volatile(s: str) -> str:
            return "\n".join(l for l in s.splitlines() if not l.startswith("-- Source:"))
        if current is None or strip_volatile(current) != strip_volatile(text):
            print(f"{args.out} is stale relative to {args.seed} -- run `python scripts/gen_physmat.py`", file=sys.stderr)
            return 1
        print(f"{args.out} is fresh ({len(rows)} seed rows, {len(classes['fallSolids'])} fallSolids, "
              f"{len(classes['gases'])} gases, {len(classes['liquids'])} liquids)")
        return 0

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text, encoding="utf-8")
    print(f"wrote {args.out} ({len(rows)} seed rows -> {len(classes['fallSolids'])} fallSolids, "
          f"{len(classes['gases'])} gases, {len(classes['liquids'])} liquids, "
          f"{len(classify(rows).get('gases', []))} gases total)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
